#version 460 core

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0) writeonly buffer OutputData {
    uint data[];
} outputData;

layout(constant_id = 0) const uint width = 1024;
layout(constant_id = 1) const uint height = 1024;

void main() {
    if (gl_GlobalInvocationID.x >= width || gl_GlobalInvocationID.y >= height) {
        return;
    }
    outputData.data[gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * width] = 0;
}